### ISSUE TITLE
no such table: bbs_category

### ISSUE THREAD

**Issue by miketwais** [isaced/NSLoger#5]
I have run this app,and it appears no such table: bbs_category,why?
![qq 20170919102057](https://user-images.githubusercontent.com/2859113/30573055-276aa172-9d24-11e7-9a39-f21946ce09a5.png)

**Comment by miketwais** [comment]
我手动创建表后，仍然报错提示需要安装:misaka

Invalid template library specified. ImportError raised when trying to load 'bbs.templatetags.bbstag': No module named 'misaka'
我在pycharm中安装misaka,为什么提示报错：
![qq 20170919133748](https://user-images.githubusercontent.com/2859113/30577275-d1cb0c9a-9d3f-11e7-9639-7edf7ed5b852.png)

**Comment by isaced** [comment]
Django 项目建立数据库和表都是通过其命令行工具执行 `migrate` 完成，不能手动去创建。

关于依赖的三方包都写在了 [requirements.txt](https://github.com/isaced/NSLoger/blob/master/requirements.txt)，用 pip 可以直接全部安装。
